# .github/workflows/publish.yml
name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      # Install Bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      # Verify Bun installation
      - run: bun --version
      
      # Publish to JSR
      - run: bun x jsr publish