# .github/workflows/publish.yml

name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: curl -fsSL https://bun.sh/install | bash
      - run: export PATH="$HOME/.bun/bin:$PATH"
      - run: bunx jsr publish
